import '@repo/ui/globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { GraphqlProvider } from '../providers/gql-provider';
import AuthProvider from '../providers/auth';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Turborepo',
  description: 'Generated by create turbo',
  robots: {
    index: false,
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }): JSX.Element {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <AuthProvider>
          <GraphqlProvider>{children}</GraphqlProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
