name: Deploy Backend (Preview)

env:
  AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
  REGION: 'ap-northeast-1'
  APP_NAME: ${{ github.event.repository.name }}
  ENV: 'dev'
  KEY: 'turborepo-test/develop'
  COGNITO_USER_POOL_ID: ${{ secrets.COGNITO_USER_POOL_ID }}

on:
  push:
    branches:
      - develop
    paths:
      - 'apps/**'
      - 'packages/**'

jobs:
  Deploy-Backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.2
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - uses: pnpm/action-setup@v4

      - name: Generate backend.conf
        run: |
          cat <<EOF > backend.conf
          key = "${KEY}"
          region = "${REGION}"
          access_key = "${AWS_ACCESS_KEY}"
          secret_key = "${AWS_SECRET_KEY}"
          EOF
        working-directory: ./apps/api/terraform

      - name: Terraform Init
        run: terraform init -backend-config=backend.conf
        working-directory: ./apps/api/terraform

      - name: Generate terraform.tfvars
        run: |
          cat <<EOF > terraform.tfvars
          app_name = "${APP_NAME}"
          env = "${ENV}"
          region = "${REGION}"
          access_key = "${AWS_ACCESS_KEY}"
          secret_key = "${AWS_SECRET_KEY}"
          user_pool_id = "${COGNITO_USER_POOL_ID}"
          callback_url = "https://${APP_NAME}-git-develop-tanakaluckys-projects.vercel.app/api/auth/callback/cognito"
          EOF
        working-directory: ./apps/api/terraform

      - name: Install Dependencies
        run: pnpm i
        working-directory: ./apps/api

      - name: Build
        run: pnpm build
        working-directory: ./apps/api/

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./apps/api/terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./apps/api/terraform

      - name: Set Outputs
        id: outputs
        run: |
          echo "graphql_url=$(terraform output -raw graphql_url)" >> "$GITHUB_OUTPUT"
          echo "cognito_client_id=$(terraform output -raw cognito_client_id)" >> "$GITHUB_OUTPUT"
          echo "cognito_client_secret=$(terraform output -raw cognito_client_secret)" >> "$GITHUB_OUTPUT"
          echo "cognito_issuer=$(terraform output -raw cognito_issuer)" >> "$GITHUB_OUTPUT"
        working-directory: ./apps/api/terraform
