name: GitHub Actions Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - develop
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.2
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - uses: pnpm/action-setup@v4

      - name: Generate backend.conf
        env:
          KEY: 'turborepo-test/develop'
          REGION: 'ap-northeast-1'
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        run: |
          cat <<EOF > backend.conf
          key = "${KEY}"
          region = "${REGION}"
          access_key = "${AWS_ACCESS_KEY}"
          secret_key = "${AWS_SECRET_KEY}"
          EOF
        working-directory: ./apps/api/terraform

      - name: Terraform Init
        run: terraform init -backend-config=backend.conf
        working-directory: ./apps/api/terraform

      - name: Generate terraform.tfvars
        env:
          APP_NAME: 'turborepo-test'
          ENV: 'dev'
          REGION: 'ap-northeast-1'
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        run: |
          cat <<EOF > terraform.tfvars
          app_name = "${APP_NAME}"
          env = "${ENV}"
          region = "${REGION}"
          access_key = "${AWS_ACCESS_KEY}"
          secret_key = "${AWS_SECRET_KEY}"
          EOF
        working-directory: ./apps/api/terraform

      - name: Install Dependencies
        run: pnpm i
        working-directory: ./apps/api

      - name: Build Lambda Source
        run: pnpm build
        working-directory: ./apps/api/

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./apps/api/terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./apps/api/terraform

      - name: Set GraphQL URL to GITHUB_OUTPUT
        id: set_graphql_url
        run: echo "graphql_url=$(terraform output -raw graphql_url)" >> "$GITHUB_OUTPUT"
        working-directory: ./apps/api/terraform

      - name: Set Api Key to GITHUB_OUTPUT
        id: set_api_key
        run: echo "api_key=$(terraform output -raw api_key)" >> "$GITHUB_OUTPUT"
        working-directory: ./apps/api/terraform

      - name: Install Vercel CLI
        run: pnpm i -g vercel@latest

      - name: Clear Vercel Environment Variables
        run: |
          vercel env rm API_KEY preview --yes --token=${{ secrets.VERCEL_TOKEN }}
          vercel env rm GRAPHQL_URL preview --yes --token=${{ secrets.VERCEL_TOKEN }}

      - name: Set Vercel Environment Variables
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          API_KEY: ${{ steps.set_api_key.outputs.api_key }}
          GRAPHQL_URL: ${{ steps.set_graphql_url.outputs.graphql_url }}
        run: |
          echo $API_KEY | vercel env add API_KEY preview --token $VERCEL_TOKEN
          echo $GRAPHQL_URL | vercel env add GRAPHQL_URL preview --token $VERCEL_TOKEN

      - name: Pull Vercel Environment Information
        run: vercel env pull ./apps/web/.env --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
